FROM golang:1.11-stretch
RUN apt-get update && apt-get install -y vim tree lsof
ENV GOPATH=/home/hdfchain/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin
ENV DCRSRC_PATH=$GOPATH/src/github.com/hdfchain/hdfdata/
ENV GO111MODULE=on
RUN useradd hdfchain -m -s /bin/bash && chown -R hdfchain:hdfchain /home/hdfchain
WORKDIR $DCRSRC_PATH
RUN chown -R hdfchain:hdfchain $GOPATH
USER hdfchain
# since we might be rebulding often we need to cache this module layer
# otherwise docker will detect changes everytime and re-download everything again
COPY go.* $DCRSRC_PATH
RUN go mod download
COPY . $DCRSRC_PATH
RUN go build
CMD /bin/bash
ENTRYPOINT ./hdfdata
# Note: when building the --squash flag is an experimental feature as of Docker 18.06
# docker build --squash -t hdfchain/hdfdata .
# running
# docker run -ti --rm hdfchain/hdfdata
# or if attaching source volume and developing interactively
# docker run -ti --entrypoint=/bin/bash -v ${PWD}:${PWD}:/home/hdfchain/go/src/github.com/hdfchain/hdfdata --rm hdfchain/hdfdata